# Generated by Django 2.2 on 2021-06-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_myprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
