# Generated by Django 2.2 on 2021-06-12 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20210612_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=80)),
                ('skill_description', models.TextField()),
                ('years_experience', models.IntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_skills', to='myprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=80)),
                ('skill_description', models.TextField()),
                ('years_experience', models.IntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='myprofile.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
