# Generated by Django 2.2 on 2021-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20210612_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='freelancing',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=50),
        ),
    ]
