# Generated by Django 2.2 on 2021-06-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='skill_level',
            field=models.CharField(choices=[('newbie', 'Newbie'), ('intermediate', 'Intermediate'), ('professional', 'Professional'), ('expert', 'Expert')], default='--------', max_length=30),
        ),
    ]
