# Generated by Django 2.2 on 2021-06-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='image/')),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='myprofile.MyProfile')),
            ],
        ),
    ]
